# Generated by Django 6.0.6 on 2026-06-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelRecord',
        ),
    ]
