# Generated by Django 6.0.6 on 2026-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('odometer', models.FloatField(verbose_name='総走行距離（km）')),
                ('fuel_liters', models.FloatField(verbose_name='給油量(L)')),
                ('price_per_liter', models.IntegerField(blank=True, null=True, verbose_name='ガソリン単価（円）')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='メモ')),
            ],
        ),
    ]
