# Generated by Django 6.0.6 on 2026-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交換日')),
                ('odometer', models.IntegerField(verbose_name='走行距離（km）')),
                ('interval', models.IntegerField(default=3000, verbose_name='交換時期（km）')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='給油金額（円）'),
        ),
    ]
