# Generated by Django 6.0.6 on 2026-06-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_maintenancerecord_fuelrecord_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='fuel_efficiency_value',
            field=models.FloatField(blank=True, null=True, verbose_name='燃費（km/L）'),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='odometer_diff',
            field=models.FloatField(blank=True, null=True, verbose_name='走行距離差（km）'),
        ),
    ]
