# Generated by Django 6.0.6 on 2026-06-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_fuelrecord_fuel_efficiency_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dashboard/')),
            ],
        ),
    ]
